name: Generate Icon Details

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *' # every morning at 9am

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: false

      - name: Generate
        run: go run main.go

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: Updated icon details'
